# user-service/docker-compose.yml
version: '3.8'

services:
  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-app
    volumes:
      - .:/var/www
    networks:
      - zama_net
    depends_on:
      user_db:
        condition: service_healthy

  user_web:
    image: nginx:alpine
    container_name: user-service-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - zama_net
    depends_on:
      - user_app

  user_db:
    image: mysql:8.0
    container_name: mysql_user_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_users
      MYSQL_USER: zama_user
      MYSQL_PASSWORD: secret
    volumes:
      - user_db_data:/var/lib/mysql
    networks:
      - zama_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  zama_net:
    external: true

volumes:
  user_db_data:
